* 4 Hour Work Week
** Step 2: Elimination
*** The End of Time Management
- For non-employees, use D-E-A-L
- For employees, use D-E-L-A
**** Being Effective vs Being Efficient
/What/ you do is infinitely more important than /how/ you do it
**** Pareto and his garden: 80/20 and freedom from utility
***** Pareto's Law
****** 80% of the outputs result from 20% of the inputs.
Alternative ways to phrase this, depending on the context, include:
- 80% of the consequences flow from 20% of the causes.
- 80% of the results come from 20% of the effort and time.
- 80% of company profits come from 20% of the products and customers.
- 80% of all stock market gains are realized by 20% of the investors and 20% of an individual portfolio.
****** Ask yourself this 
1. Which 20% of sources are causing 80% of my problems and unhappiness?
2. Which 20% of sources are resulting in 80% of my desired outcomes and happiness?
****** Slow down and remember this
Most things make no difference. /Being busy is a form of laziness—lazy thinking and indiscriminate action/.
**** The 9-5 Illusion and Parkinson's Law
***** Parkinson's Law
****** A task will swell in (perceived) importance and complexity in relation to the time allotted for its completion
***** Synergistic Approaches for increasing productivity
****** Limit tasks to the important to shorten work time (80/20)
****** Shorten work time to limit tasks to the important (Parkinson's Law)
***** The best solution is to use both together:
****** Identify the few critical tasks that contribute most to income
****** Schedule them with /very short/ and clear deadlines
**** Question and Actions
***** If you had a heart attack and had to work two hours per day, what would you do?
***** If you had a second heart attack and had to work two hours per /week/, what would you do?
***** If you had a gun to your head and /had/ to stop doing 4/5 of different time-consuming activities, what would you remove?
***** What are the top-three activities that I use to fill time to feel as though I've been productive?
***** Who are the 20% of people who produce 80% of your enjoyment and propel you forward, and which 20% cause 80% of your depression, anger and second-guessing?
****** Positive friends versus time-consuming friends: Who is helping versus hurting you, and how do you increase your time with the former while decreasing or eliminating your time with the latter?
****** Who is causing me stress disproportionate to the time I spend with them? What will happen if I simply stop interacting with these people? Fear-setting helps here.
****** When do I feel starved for time? What commitments, thoughts, and people can I eliminate to fix this problem?
***** Learn to ask, “If this is the only thing I accomplish today, will I be satisfied with my day?”
***** Put a Post-it on your computer screen or set an Outlook reminder to alert you at least three times daily with the question: Are you inventing things to do to avoid the important?
***** Do not multitask.
***** Use Parkinson’s Law on a Macro and Micro Level
*** The Low-Information Diet
**** Cultivating Selective Ignorance
There are many things of which a wise man might wish to be ignorant - Ralph Waldo Emerson(1803-1882)
- Gives you something new to ask the rest of the population in lieu of small talk?
**** Questions and Actions
***** Go on an immediate one-week media fast
- No newspapers, magazines, audiobooks, or nonmusic radio. Music is permitted at all times.
- No news websites whatsoever (cnn.com, drudgereport.com, msn.com,10 etc.).
- No television at all, except for one hour of pleasure viewing each evening.
- No reading books, except for this book and one hour of fiction11 pleasure reading prior to bed.
- No web surfing at the desk unless it is necessary to complete a work task for that day. Necessary means necessary, not nice to have.
***** Develop the habit of asking yourself, "Will I definitely use this information for something immediate and important?"
** Comfort Challenges
*** Learn to Eye Gaze(2 Days)
For the next two days, practice gazing into the eyes of others—whether people you pass on the street or conversational partners—until they break contact. Hints:

1. Focus on one eye and be sure to blink occasionally so you don’t look like a psychopath or get your ass kicked.
2. In conversation, maintain eye contact when you are speaking. It’s easy to do while listening.
3. Practice with people bigger or more confident than yourself. If a passerby asks you what the hell you’re staring at, just smile and respond, "Sorry about that. I thought you were an old friend of mine."
*** Learn to Propose(2 Days)
Stop asking for opinions and start proposing solutions. Begin with the small things. If someone is going to ask, or asks, "Where should we eat?" "What movie should we watch?" "What should we do tonight?" or anything similar, do NOT reflect it back with, "Well, what do you want to … ?" Offer a solution. Stop the back-and-forth and make a decision. Practice this in both personal and professional environments. Here are a few lines that help (my favorites are the first and last):
"Can I make a suggestion?"
"I propose ..."
"I’d like to propose..." 
"I suggest that ... What do you think?"
"Let’s try ... and then try something else if that doesn’t work."
